# Generated by Django 3.2.3 on 2021-05-26 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0002_alter_table_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_slots',
        ),
    ]
