# Generated by Django 3.2.3 on 2021-05-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0004_alter_table_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date_time_end',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date_time_start',
            field=models.DateTimeField(unique=True),
        ),
    ]
